[touch]
enabled = true
finale_port = "COM23"
dx_p1_port = "COM6"
dx_p2_port = "COM8"

[jvs]
enabled = true
port = "COM23"

[jvs.input]
service = 51
test = 84
p1_btn1 = 87
p1_btn2 = 69
p1_btn3 = 68
p1_btn4 = 67
p1_btn5 = 88
p1_btn6 = 90
p1_btn7 = 65
p1_btn8 = 81
p2_btn1 = 104
p2_btn2 = 105
p2_btn3 = 102
p2_btn4 = 99
p2_btn5 = 98
p2_btn6 = 97
p2_btn7 = 100
p2_btn8 = 103

[reader]
enabled = false
port = "COM24"
device_file = "./device.txt"
