[settings]
disable_touch=false
re2_touch_com="COM22"
alls_p1_touch_com=""
alls_p2_touch_com=""

jvs_disabled=false
re2_jvs_com=""

[input]
service=0x00
test=0x00

# COIN=0x00

# Player 1 default input, same as SEGATOOLS default keys
p1_btn1=0x57 # W
p1_btn2=0x45 # E
p1_btn3=0x44 # D
p1_btn4=0x43 # C
p1_btn5=0x58 # X
p1_btn6=0x5A # Z
p1_btn7=0x41 # A
p1_btn8=0x51 # Q

# TODO: complete example config