name: Build app

on:
  push:
    paths:
      - 'src/**'
      - '.github/**'
  pull_request:
    paths:
      - 'src/**'
      - '.github/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install latest stable rust
      uses: actions-rs/toolchain@v1
      with:
        target: x86_64-pc-windows-gnu
        override: true
        components: rustfmt, clippy
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
