name: Build

on:
  push:
    paths:
      - 'src/**'
  pull_request:
    paths:
      - 'src/**'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Install latest stable rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - uses: actions/upload-artifact@v3
      with:
        name: mai_finale_to_deluxe.exe
        path: target/release/mai_finale_to_deluxe.exe
#    - name: Publish
#      uses: softprops/action-gh-release@v1
#      if: startsWith(github.ref, 'refs/tags/v')
#      with:
#        files: |
#          target/release/mai_finale_to_deluxe.exe
